version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
    - ./data/db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    networks:
      - greetingservice_default
  book-service:
    image: 987152/books:latest
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - greetingservice_default
networks:
  greetingservice_default:

