server:
  port: 9010

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: theClient
      clentSecret: thisissecret
    resource :
      userInfoUri: http://localhost:8080/user